CREATE USER app_data IDENTIFIED BY "Passwordxxxxxx1"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

CREATE USER app_code IDENTIFIED BY "Passwordxxxxxx2"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

CREATE USER app_admin IDENTIFIED BY "Passwordxxxxxx3"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

CREATE USER app_user IDENTIFIED BY "Passwordxxxxxx4"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;